version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
    ports:
      - "8080:8080"
    image: langchain_document_loader:${LANGCHAIN_DOCUMENT_LOADER_VERSION:-latest}
    restart: always
