version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
    ports:
      # Exposes application port.
    - "8000:8000"
    volumes:
      # Adds current directory as volume.
    - .:/app/src/
    environment:
      # Enables autoreload.
      LANGCHAIN_DOCUMENT_LOADER_RELOAD: "True"
